[project]
name = "ronaldmcdonald"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "ensembledata>=0.2.4",
    "facebook-scraper>=0.2.59",
    "pytubefix>=8.12.2",
    "tiktokapi>=7.0.0",
]
